default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: janusz
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recettopia_development

test:
  <<: *default
  database: recettopia_test

production:
  <<: *default
  database: recettopia_production
